### PR TITLE
Update requirements/develop.pip with missing pyopenssl library

### PR DESCRIPTION
**Pull request by geoffreyaldebert**
Just add library which were missing when I tried to install repo locally

### CODE REVIEW

**Comment by abulte** [comment]
I just installed from `develop.pip` on a fresh virtualenv (python3.7) and did not have any issue running `nameko run croquemort.http` 🤔 

Does the error appear when doing something else (using the API...)?

What OS are you on ?

**Comment by geoffreyaldebert** [comment]
```nameko run croquemort.http``` and ```nameko run croquemort.crawler``` work after installation but the problem is appearing when you try to do some http POST or GET request once these two services are launched. 
When I try ```http :8000/check/one url="https://www.data.gouv.fr/fr/"``` I have the following error in crawler output : ``` Error with https://www.data.gouv.fr/fr/: wrap_socket() got an unexpected keyword argument '_context' ```  and I can't retrieve correct response after that. 
After ```pip install pyopenssl```, the error disappear

**Comment by geoffreyaldebert** [comment]
Tested both on Debian and Ubuntu env

**Comment by abulte** [comment]
Got it, thanks, good catch.

I think this belongs in `install.pip` rather than `develop.pip`.

Also can you add an entry to `CHANGELOG.md`, something like "Add pyOpenSSL requirement for python3.7 compatibility" (this seems specific to py3.7) ?

Thanks!

**Comment by geoffreyaldebert** [comment]
Done!

**Comment by abulte** [comment]
@geoffreyaldebert great, thanks!

**Pull request merged**
